[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"

[variables]
NODE_ENV = "production"
PORT = "8080"
RAILWAY_VOLUME_MOUNT_PATH = "/tmp/downloads"

[volumes]
downloads = "/tmp/downloads"
